[keyboard]
name = "Corne RMK"
product_name = "Corne42 rmk"
vendor_id = 0x4653
product_id = 0x0001
manufacturer = "BHE-ergo"
board = "nice!nano_v2"
vial_json = "vial_corne.json"

[aliases]
Bt1 = "User0"
Bt2 = "User1"
Bt3 = "User2"
BtNext = "User3"
BtPre = "User4"
BtClear = "User5"
BtUsb = "User6"

[layout]

matrix_map = """
            (0,0) (0,1) (0,2) (0,3) (0,4) (0,5)            (4,5) (4,4) (4,3) (4,2) (4,1) (4,0) 
            (1,0) (1,1) (1,2) (1,3) (1,4) (1,5)            (5,5) (5,4) (5,3) (5,2) (5,1) (5,0) 
            (2,0) (2,1) (2,2) (2,3) (2,4) (2,5)            (6,5) (6,4) (6,3) (6,2) (6,1) (6,0) 
                              (3,3) (3,4) (3,5)            (7,5) (7,4) (7,3)                
"""
rows = 8
cols = 6
layers = 8



[[layer]]
#layer 0 - Base
name = "base_layer"
keys = """
        Tab Q W E R T                                                Y U I O P Backslash
        Escape MT(A,LCtrl) MT(S,LAlt) MT(D,LGui) MT(F,LShift) G    H MT(J,RShift) MT(K,RGui) MT(L,RAlt) MT(Semicolon,RCtrl) Quote
        MO(4) MT(Z,LGui) X C V B                                    N M Comma Dot Slash Backspace
                               LT(6,Escape) MO(2) LT(5,Space)         Enter MO(3) LT(2,Backspace)
"""
[[layer]]
#layer 1 - Windows
name = "windows_layer"
keys = """
        __ __ __ __ __ __                                             __ __ __ __ __ __
        __ MT(A,LCtrl) MT(S,LAlt) MT(D,LCtrl) MT(F,LShift) __       __ MT(J,RShift) MT(K,RCtrl) MT(L,RAlt) MT(Semicolon,RCtrl) __
        LGui __ __ __ __ __                                          __ __ __ __ __ __
                               __ __ __                                __ __ __
"""
[[layer]]
#layer 2 - Lower/Symbols
name = "symbol_layer"
keys = """
        __ WM(Kc1,LShift) WM(Kc2,LShift) WM(Kc3,LShift) WM(Kc4,LShift) WM(Kc5,LShift)   WM(Kc6,LShift) WM(Kc7,LShift) WM(Kc8,LShift) WM(Kc9,LShift) WM(Kc0,LShift) WM(Backslash,LShift)
        __ __ LeftBracket RightBracket WM(LeftBracket,LShift) WM(RightBracket,LShift)    Equal WM(Minus,LShift) Minus WM(Equal,LShift) WM(Quote,LShift) __
        __ __ RightBracket WM(Kc9,LShift) WM(Backslash,LShift) Backslash                Slash WM(Slash,LShift) Grave WM(Grave,LShift) Quote __
                               __ __ __                                                  WM(Grave,LShift) MO(4) Grave
"""

[[layer]]
#layer 3 - Raise/Mix
name = "mix_layer"
keys = """
        __ F1 F2 F3 F4 F5                                           F6 F7 F8 F9 F10 F11
        __ Kc5 Kc4 Kc3 Kc2 Kc1                                     Backspace Minus Equal WM(Equal,LShift) Quote F12
        __ Kc6 Kc7 Kc8 Kc9 Kc0                                     Tab Insert Home End __ __
                               Tab MO(4) Backspace                      __ __ Kc3
"""
[[layer]]
#layer 4 - Adjust
name = "adjust_layer"
keys = """
        @Bt1 @BtPre __ __ __ __                                           __ __ __ __ __ __
        @Bt2 @BtNext __ __ __ __                                           TG(1) TO(0) __ __ __ TG(1)
        @Bt3 @BtClear @BtUsb @BtClear __ __                                           __ __ __ __ __ CapsLock
                               __ __ __                               __ __ Kc4
"""
[[layer]]
#layer 5 - Navigation
name = "navigation_layer"
keys = """
        __ __ __ MouseUp PageUp PageDown                            MouseBtn1 MouseBtn3 MouseBtn2 MouseWheelUp MouseWheelDown __
        __ __ MouseLeft MouseDown MouseRight MouseWheelUp           Left Down Up Right __ __
        __ __ __ __ __ MouseWheelDown                               __ __ __ __ __ __
                               MO(7) __ __                          __ __ Kc5
"""

[[layer]]
#layer 6 - Number/Keypad
name = "number_layer"
keys = """
        MO(7) __ __ __ __ __                                        Kp7 Kp8 Kp9 KpMinus KpAsterisk __
        __ __ __ __ __ __                                           Kp4 Kp5 Kp6 KpPlus KpSlash __
        __ __ __ __ __ __                                           Kp1 Kp2 Kp3 __ __ __
                               __ __ __                             Kp0 KpDot Kp0
"""

[[layer]]
#layer 7 - Debug
name = "debug_layer"
keys = """
        __ __ __ __ __ __                                           __ __ __ __ __ __
        __ __ __ __ __ __                                           __ __ __ __ __ __
        __ __ __ __ __ Bootloader                                   Bootloader __ __ __ __ __
                               __ __ __                               __ __ Kc7
"""

[storage]

enabled = true
# Set `clear_storage` to true to clear all the stored info when the keyboard boots
clear_storage = false

[ble]

enabled = true

#battery config for nicenano
battery_adc_pin = "vddh"
adc_divider_measured = 2000
adc_divider_total = 2806
default_tx_power = 8

[behavior]

tap_hold = { enable_hrm = true, permissive_hold = true, chordal_hold = true, prior_idle_time = "100ms", hold_on_other_press=true, hold_timeout = "250ms"}

[split]

connection = "ble"

[split.central]

rows = 4
cols = 6
row_offset = 0
col_offset = 0
ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]

[split.central.matrix]

## promicro pin: 4 5 6 7
input_pins = ["P0_22", "P0_24", "P1_00", "P0_11"]
## promicro pin: 21 20 19 18 15 14
output_pins = ["P0_31", "P0_29", "P0_02", "P1_15", "P1_13", "P1_11"]

[[split.peripheral]]

rows = 4
cols = 6
row_offset = 4
col_offset = 0
ble_addr = [0x7e, 0xfe, 0x73, 0x9e, 0x66, 0xe3]

[split.peripheral.matrix]

## promicro pin: 4 5 6 7
input_pins = ["P0_22", "P0_24", "P1_00", "P0_11"]
## promicro pin: 21 20 19 18 15 14
output_pins = ["P0_31", "P0_29", "P0_02", "P1_15", "P1_13", "P1_11"]


[rmk]
# Mouse key interval (ms) - controls mouse movement speed
mouse_key_interval = 20
# Mouse wheel interval (ms) - controls scrolling speed
mouse_wheel_interval = 80
debounce_time = 10
ble_profiles_num = 3
