[env]

DEVICE_NAME="corne-rmk"
KEYBOARD_TOML_PATH="${CARGO_MAKE_WORKING_DIRECTORY}/keyboard_corne.toml"
VIAL_JSON_PATH="${CARGO_MAKE_WORKING_DIRECTORY}/vial_corne.json"

[env.corne]

DEVICE_NAME="corne-rmk"
KEYBOARD_TOML_PATH="${CARGO_MAKE_WORKING_DIRECTORY}/keyboard_corne.toml"
VIAL_JSON_PATH="${CARGO_MAKE_WORKING_DIRECTORY}/vial_corne.json"

[env.keyball]

DEVICE_NAME="keyball-rmk"
KEYBOARD_TOML_PATH="${CARGO_MAKE_WORKING_DIRECTORY}/keyboard_keyball61.toml"
VIAL_JSON_PATH="${CARGO_MAKE_WORKING_DIRECTORY}/vial_corne.json"



[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = ["-h"] }

[tasks.objcopy-central]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
script = """

cargo objcopy --release --bin central -- \
    -O ihex ${DEVICE_NAME}-central.hex
"""
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-peripheral]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "peripheral",
    "--",
    "-O",
    "ihex",
    "${DEVICE_NAME}-peripheral.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.uf2-central]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "${DEVICE_NAME}-central.hex",
    "--output-path",
    "${DEVICE_NAME}-central.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-central"]

[tasks.uf2-peripheral]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "${DEVICE_NAME}-peripheral.hex",
    "--output-path",
    "${DEVICE_NAME}-peripheral.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-peripheral"]

[tasks.release]
script = """
cargo build --release 
"""

[tasks.build]
args = ["build", "--verbose"]

[tasks.uf2]
dependencies = ["uf2-central", "uf2-peripheral"]

[tasks.show-env]

description = "Displays the active environment variables based on the selected profile."
script = [
    "echo '--- Current Environment Variables ---'",
    "echo 'KEYBOARD_TOML_PATH: '${KEYBOARD_TOML_PATH}",
    "echo 'VIAL_JSON_PATH: '${VIAL_JSON_PATH}",
    "echo '-------------------------------------'"
]

